INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('admin', 'admin@hotmail.com','00000000000','admin123', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Luiz Henrique de Barros de Oliveira', 'hick@gmail.com','00000000001','senhahick', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Luiz Paulo de Barros de Oliveira', 'luiz@gmail.com','00000000002','senhaluiz', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Luis Otávio Capelari', 'luis@gmail.com','00000000003','senhaluis', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Rafael Menezes', 'rafael@gmail.com','00000000004','senharafael', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Michel Gomes de Souza', 'michel@gmail.com','00000000005','senhamichel', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Juliano Cezar Petini', 'juliano@gmail.com','00000000006','senhajuliano', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Daniel Rodrigues Farina', 'daniel@gmail.com','00000000007','senhadaniel', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Willian Rodrigues', 'willian@gmail.com','00000000008','senhawillian', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Matheus Souza Viera','matheus@gmail.com','00000000009','senhamatheus', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Marcos Silvano Pereira', 'marcos@gmail.com','00000000010','senhamarcos', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Andre Kawamoto', 'andre@gmail.com','00000000011','senhaandre', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Ivanilton Polato', 'ivanilton@gmail.com','00000000012','senhaivanilton', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Paola Silva Oliveira', 'paola@gmail.com','00000000013','senhapaola', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Marcos Aurelio Gracioto', 'gracioto@gmail.com','00000000014','senhagracioto', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Jessica Mendes', 'jessica@gmail.com','00000000015','senhajessica', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Claudia Silva Renner', 'claudia@gmail.com','00000000016','senhaclaudia', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Maria Isabela Moreira', 'maria@gmail.com','00000000017','senhamaria', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Sofia Cortegana', 'sofia@gmail.com','00000000018','senhasofia', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Karina Marques Rocha', 'karina@gmail.com','00000000019','senhakarina', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('José da Rocha Silva', 'jose@gmail.com','00000000020','senhajose', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('João Paulo Crispane', 'joao@gmail.com','00000000021','senhajoao', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Maria Joaquina Gomes', 'joaquina@gmail.com','00000000022','senhajoaquina', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Renata Vilvert', 'renata@gmail.com','00000000023','senharenata', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Rodrigo Cristovão', 'rodrigo@gmail.com','00000000024','senharodrigo', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Vinicius Carrara', 'vinicius@gmail.com','00000000025','senhavinicius', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Maria Eduarda Souza', 'eduarda@gmail.com','00000000026','senhaeduarda', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Angélica Natalina', 'angelica@gmail.com','00000000027','senhaangelica', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Jaqueline Rezende', 'jaqueline@gmail.com','00000000028','senhajaqueline', '0', '0');
INSERT INTO `seinfo`.`pessoa` (`nome`, `email`, `CPF`, `senha`, `nivel`, `classificacao`) VALUES ('Antonio Marcos da Silva', 'antonio@gmail.com','00000000029','senhaantonio', '0', '0');

